"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$username\
[](bg:mauve fg:surface0)\
[$directory](bg:mauve fg:crust)\
[](bg:surface0 fg:mauve)\
[$git_branch](fg:peach bg:surface0)\
$git_status\
[$time](fg:overlay1 bg:surface0)\
[ ](fg:surface0)\
$cmd_duration\
$line_break\
$character"""

palette = 'catppuccin_mocha'

[username]
show_always = true
style_user = 'bg:surface0 fg:mauve'
style_root = 'bg:surface0 fg:red'
format = '[ $user ]($style)'

[directory]
format = ' $path '
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[git_branch]
symbol = ''
format = ' $symbol $branch'

[git_status]
format = '([ ](bg:surface0)[](bg:peach fg:surface0)[ $all_status$ahead_behind](fg:crust bg:peach)[](fg:peach bg:surface0))'
ahead = ' '
behind = ' '
conflicted = '= '
deleted = '× '
diverged = '󰘖 '
modified = '± '
renamed = '» '
stashed = ' '
staged = '+ '
untracked = '󱀶 '

[time]
disabled = false
time_format = "%R"
format = '  $time '

[cmd_duration]
show_milliseconds = true
format = '[ in $duration](fg:overlay1)'
disabled = false
show_notifications = true
min_time_to_notify = 45000

[line_break]
disabled = false

[character]
success_symbol = '[❯](fg:overlay0)'
error_symbol = '[❯](fg:red)'

[palettes.catppuccin_mocha]
rosewater = '224'
flamingo = '224'
pink = '218'
mauve = '183'
red = '211'
maroon = '217'
peach = '216'
yellow = '223'
green = '151'
teal = '116'
sky = '117'
sapphire = '117'
blue = '111'
lavender = '147'
text = '189'
subtext1 = '146'
subtext0 = '146'
overlay2 = '103'
overlay1 = '103'
overlay0 = '60'
surface2 = '59'
surface1 = '17'
surface0 = '16'
base = '16'
mantle = '16'
crust = '16'

