"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$username\
[](bg:mauve fg:surface0)\
[$directory](bg:mauve fg:crust)\
[](bg:surface0 fg:mauve)\
[$git_branch](fg:peach bg:surface0)\
$git_status\
[$time](fg:overlay1 bg:surface0)\
[ ](fg:surface0)\
$cmd_duration\
$line_break\
$character"""

palette = 'catppuccin_mocha'

[username]
show_always = true
style_user = 'bg:surface0 fg:mauve'
style_root = 'bg:surface0 fg:mauve'
format = '[ $user ]($style)'

[directory]
format = ' $path '
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ''
'Music' = '󰝚'
'Pictures' = ''
'Developer' = '󰲋'

[git_branch]
symbol = ''
format = ' $symbol $branch'

[git_status]
format = '([ ](bg:surface0)[](bg:peach fg:surface0)[ $all_status$ahead_behind](fg:crust bg:peach)[](fg:peach bg:surface0))'
ahead = ' '
behind = ' '
conflicted = '= '
deleted = '✘ '
diverged = '󰘖 '
modified = '± '
renamed = '» '
stashed = ' '
staged = '+ '
untracked = '󱀶 '

[time]
disabled = false
time_format = "%R"
format = '  $time '

[cmd_duration]
show_milliseconds = true
format = '[ in $duration](fg:overlay1)'
disabled = false
show_notifications = true
min_time_to_notify = 45000

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:overlay0)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[palettes.catppuccin_mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'
